import * as charts from "@/components/Chart";
import {
  Date as DateIcon,
  Kanban as KanbanIcon,
  Kind as KindIcon,
  Map as MapIcon,
  Multiple as MultipleIcon,
  RichText as RichTextIcon,
  Single as SingleIcon,
  Sunburst as SunburstIcon,
  Table as TableIcon,
  Timeline as TimelineIcon,
  TreeMap as TreeMapIcon,
  Statistic as StatisticIcon,
  Button as ButtonIcon,
  GuageChart as GuageChartIcon,
  ProfileChart as ProfileChartIcon,
  GattChart as GattChartIcon,
  CandlestickChart as CandlestickChartIcon,
  RaceChart as RaceChartIcon
} from "@/assets/Icon";

import {
  AreaChartOutlined,
  FileTextOutlined,
  CheckSquareOutlined,
  BarChartOutlined,
  LineChartOutlined,
  PieChartOutlined ,
  RadarChartOutlined ,
  FileMarkdownOutlined ,
  PercentageOutlined ,
  TagsOutlined ,
  PhoneOutlined ,
  SnippetsOutlined ,
  MailOutlined ,
  LinkOutlined ,
  MenuOutlined ,
  NumberOutlined ,
  PaperClipOutlined ,
  StarOutlined,
  DotChartOutlined,
  HeatMapOutlined 
 } from '@ant-design/icons'


export const components = {
  ...charts,
}

export const icons = {
  // 基础类别
  DataTable: TableIcon,
  Kanban: KanbanIcon,
  Text: FileTextOutlined,
  Number: NumberOutlined ,
  Check: CheckSquareOutlined,
  Single: SingleIcon,
  Multiple: MultipleIcon,
  Date: DateIcon,
  Attachment: PaperClipOutlined ,
  Rating: StarOutlined,
  Kind: KindIcon,
  Statistic: StatisticIcon,
  Button: ButtonIcon,
  Menu: MenuOutlined ,
  Link: LinkOutlined ,
  Mail: MailOutlined ,
  Phone: PhoneOutlined ,
  Join: SnippetsOutlined ,
  Tags: TagsOutlined ,
  Percent: PercentageOutlined ,
  RichText: RichTextIcon,
  Markdown: FileMarkdownOutlined ,
  // 图表类别
  BarChart: BarChartOutlined,
  LineChart: LineChartOutlined ,
  PieChart: PieChartOutlined ,
  RadarChart: RadarChartOutlined ,
  ScatterChart: DotChartOutlined,
  SunburstChart: SunburstIcon,
  RaceChart: RaceChartIcon,
  MapChart: MapIcon,
  GuageChart: GuageChartIcon,
  ProfileChart: ProfileChartIcon,
  HeatmapChart: HeatMapOutlined ,
  GattChart: GattChartIcon,
  CandlestickChart: CandlestickChartIcon,
  TreemapChart: TreeMapIcon,
  TimelineChart: TimelineIcon,
}