import * as charts from "@/components/Chart";
import {
  AreaChartOutlined,
  FileTextOutlined,
  CheckSquareOutlined,
  BarChartOutlined,
  LineChartOutlined,
  PieChartOutlined ,
  RadarChartOutlined ,
  FileMarkdownOutlined ,
  PercentageOutlined ,
  TagsOutlined ,
  PhoneOutlined ,
  SnippetsOutlined ,
  MailOutlined ,
  LinkOutlined ,
  MenuOutlined ,
  NumberOutlined ,
 } from '@ant-design/icons'


export const components = {
  ...charts,
}

export const icons = {
  // 基础类别
  DataTable: AreaChartOutlined,
  Kanban: AreaChartOutlined,
  Text: FileTextOutlined,
  Number: NumberOutlined ,
  Check: CheckSquareOutlined,
  Single: AreaChartOutlined,
  Multiple: AreaChartOutlined,
  Date: AreaChartOutlined,
  Attachment: AreaChartOutlined,
  Rating: AreaChartOutlined,
  Kind: AreaChartOutlined,
  Statistic: AreaChartOutlined,
  Button: AreaChartOutlined,
  Menu: MenuOutlined ,
  Link: LinkOutlined ,
  Mail: MailOutlined ,
  Phone: PhoneOutlined ,
  Join: SnippetsOutlined ,
  Tags: TagsOutlined ,
  Percent: PercentageOutlined ,
  RichText: AreaChartOutlined,
  Markdown: FileMarkdownOutlined ,
  // 图表类别
  BarChart: BarChartOutlined,
  LineChart: LineChartOutlined ,
  PieChart: PieChartOutlined ,
  RadarChart: RadarChartOutlined ,
  ScatterChart: AreaChartOutlined,
  SunburstChart: AreaChartOutlined,
  RaceChart: AreaChartOutlined,
  MapChart: AreaChartOutlined,
  GuageChart: AreaChartOutlined,
  ProfileChart: AreaChartOutlined,
  HeatmapChart: AreaChartOutlined,
  GattChart: AreaChartOutlined,
  CandlestickChart: AreaChartOutlined,
  TreemapChart: AreaChartOutlined,
  TimelineChart: AreaChartOutlined,
}